---
- name: create a folder  
  hosts: all  
  tasks: 
  - name: Restrict write and execute access to User IK
    win_acl:
        user: user_IK
        path: C:\\test.conf
        type: allow
        rights: Fullcontrol
...