---
- name: Creating Users
  hosts: all
  tasks:
  - name: Creating a local account
    win_user:
      name: IK2
      state: present

  - name: Create a local profile 
    win_user_profile:
      username: IK2
      state: present

  - name: Adding a local and domain user to a local group.
    win_group_membership:
      name: IKdeploy
      members:
      - IK2
      state: present
...