---
- name: Creating Users
  hosts: all
  tasks:
  - name: Creating a local account
    win_user:
      name: IK2
      state: present
  - name: Create a local profile 
    win_user_profile:
      uisername: IK2
      state: present
...