--- 
- name: testing firewalls 
  hosts: all  
  tasks:  
  - name: Denying port 80
    win_firewall_rule:
      name: testing
      state: present
      enable: true
      localport: 80
      action: block
      direction: In
      protocol: TCP
...